version: '3.3'
services:
    python-nginx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: python-nginx
        tty: true
        image: python_nginx:latest
        ports:
            - 80:9000
        expose:
            - 900
        restart: always

    postgres:
        container_name: postgresdb
        tty: true
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: postgres123
        ports:
            - 5432:5432
        expose:
            - 5432
        restart: always
